from rest_framework import serializers
from .models import Book

class BookSerializer(serializers.ModelSerializer):
    """
    Serializer for the Book model.

    This serializer automatically generates fields based on the Book model
    definition. It ensures that Book instances can be easily converted to
    and from JSON for API responses and requests.

    Fields included:
        - id: AutoField (primary key, generated by Django)
        - title: CharField (title of the book)
        - author: CharField (author of the book)
    """

    class Meta:
        model = Book
        fields = '__all__'  # include all fields defined in the Book model
        # Alternatively, you could explicitly list fields for clarity:
        # fields = ['id', 'title', 'author'] and added ['published_date', 'created_at']

